name: Free iOS Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install System Dependencies
        run: |
          brew install cocoapods

      - name: Clear Cache and Get Packages
        run: |
          flutter clean
          flutter pub get

      - name: Setup iOS Pods
        run: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS Payload (Unsigned IPA)
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r app-release.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: app-release.ipa